module.exports = {
  firstSidebar: [
    "_index",
    {
      type: "ref",
      id: "rural-generalist/introduction",
    },
    {
      type: "ref",
      id: "fellowship-training/standards",
    },
    {
      type: "ref",
      id: "fellowship-assessment/standards",
    },
    {
      type: "ref",
      id: "supervisors-training-posts/standards",
    },
    {
      type: "ref",
      id: "training-org/standards",
    },
  ],
  "Fellowship Training": ["fellowship-training/standards"],
  "Fellowship Assessment": ["fellowship-assessment/standards"],
  "Supervisors and Training Posts Standards": [
    "supervisors-training-posts/standards",
  ],
  "Training Organisations Standards": ["training-org/standards"],
  "Rural Generalist": [
    "rural-generalist/introduction",
    "rural-generalist/curriculum",
    "rural-generalist/competency-domains",
    "rural-generalist/learning-areas",
    {
      type: "category",
      label: "All Learning Areas",
      items: [
        "rural-generalist/learning-areas/aboriginal-and-torres-strait-islander-health",
        "rural-generalist/learning-areas/academic-practice",
        "rural-generalist/learning-areas/addictive-behaviours",
        "rural-generalist/learning-areas/adult-internal-medicine",
        "rural-generalist/learning-areas/aged-care",
        "rural-generalist/learning-areas/anaesthetics",
        "rural-generalist/learning-areas/chronic-disease",
        "rural-generalist/learning-areas/collaborator",
        "rural-generalist/learning-areas/communicator",
        "rural-generalist/learning-areas/dermatology",
        "rural-generalist/learning-areas/diagnostic-imaging",
        "rural-generalist/learning-areas/differential-diagnosis",
        "rural-generalist/learning-areas/digital-health",
        "rural-generalist/learning-areas/emergency",
        "rural-generalist/learning-areas/genetics",
        "rural-generalist/learning-areas/health-advocate",
        "rural-generalist/learning-areas/history-taking",
        "rural-generalist/learning-areas/investigations",
        "rural-generalist/learning-areas/leader",
        "rural-generalist/learning-areas/mental-health",
        "rural-generalist/learning-areas/musculoskeletal",
        "rural-generalist/learning-areas/obstetrics-and-gynaecology",
        "rural-generalist/learning-areas/occupational-health",
        "rural-generalist/learning-areas/ophthalmology",
        "rural-generalist/learning-areas/oral-health",
        "rural-generalist/learning-areas/paediatrics",
        "rural-generalist/learning-areas/palliative-care",
        "rural-generalist/learning-areas/pharmaceuticals",
        "rural-generalist/learning-areas/physical-examination",
        "rural-generalist/learning-areas/population-health",
        "rural-generalist/learning-areas/procedural-skills",
        "rural-generalist/learning-areas/professional",
        "rural-generalist/learning-areas/rehabilitation",
        "rural-generalist/learning-areas/remote-medicine",
        "rural-generalist/learning-areas/scholar",
        "rural-generalist/learning-areas/sexual-health",
        "rural-generalist/learning-areas/surgery",
      ],
    },
  ],
};
